# Generated by Django 4.0.6 on 2022-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medStore', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
