# Generated by Django 4.0.6 on 2022-08-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medStore', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
