# Generated by Django 4.0.6 on 2022-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medStore', '0006_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('sub', models.CharField(max_length=200, null=True)),
                ('msg', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
