# Generated by Django 4.0.6 on 2022-09-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medStore', '0008_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
